# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

# Inspired on https://github.com/juliasilge/tidytext
environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true

build_script:
  - travis-tool.sh install_github ropensci/beautier
  - travis-tool.sh install_github ropensci/tracerer
  - travis-tool.sh install_github ropensci/beastier
  - travis-tool.sh install_github ropensci/mauricer
  - # Rscript -e "source(\"R/install_beast2.R\"); source(\"R/get_default_beast2_download_url.R\"); source(\"R/check_os.R\"); install_beast2()"
  - # Rscript -e "source(\"R/get_default_beast2_folder.R\"); source(\"R/get_default_beast2_jar_path.R\"); source(\"R/check_os.R\"); print(get_default_beast2_jar_path())"

test_script:
  - Rscript scripts/mauricer_self_test.R
  - # travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
